#!/bin/bash
# ati script

echo For ATI open utility to find the ipAddress or set a static ipAddress
echo put address in ati_ethernetInterface.xml
echo verify calibration file name matches the sensor
echo assuming previous mentioned steps are already accounted for
cd ATI_Ethernet
 yarprobotinterface --config ati_ethernetInterface.xml
cd ..
