#!/bin/bash
# Startup script for the ftShoes

echo ftShoes startup
echo executing ESDcan commands
 sudo ip link set can0 type can bitrate 1000000
 sudo ip link set up can0
echo Verify correct values for FT/sense
echo address tipical value 0x0D
echo Device number is Net0
 yarprobotinterface --config ../conf/ftshoes_yarprobotinterface_right.xml
 yarprobotinterface --config ../conf/ftshoes_yarprobotinterface_left.xml
